import { Schema } from "effect"

import {
  toDraft07JsonSchema,
  withJsonSchemaPropertyDescriptions,
  withJsonSchemaUnionPropertyDescriptions
} from "./json-schema.js"

import { ModelIdentifier } from "./model-administration.js"
import { HulySequenceId, HulySequencePrefix, HulySequenceSummarySchema } from "./sdk-discovery-configurations.js"

export const SequenceIdentifier = Schema.Trimmed.check(Schema.isNonEmpty())
  .pipe(Schema.brand("SequenceIdentifier"))
  .annotate({
    description: "Exact sequence ID or attached class ID/name. Resolution tries sequence ID first, then class."
  })
export type SequenceIdentifier = Schema.Schema.Type<typeof SequenceIdentifier>

const ConfirmSequenceWrite = Schema.Literal(true).annotate({
  description: "Must be true to acknowledge that this operation changes a Huly sequence definition."
})

const CreateStandardSequenceParamsSchema = Schema.Struct({
  class: ModelIdentifier.annotate({ description: "Attached class ID or exact class name/label." }),
  kind: Schema.Literal("standard"),
  confirm: ConfirmSequenceWrite
})

const CreateCustomSequenceParamsSchema = Schema.Struct({
  class: ModelIdentifier.annotate({ description: "Attached class ID or exact class name/label." }),
  kind: Schema.Literal("custom"),
  prefix: HulySequencePrefix,
  confirm: ConfirmSequenceWrite
})

export const CreateHulySequenceParamsSchema = Schema.Union([
  CreateStandardSequenceParamsSchema,
  CreateCustomSequenceParamsSchema
]).annotate({ title: "CreateHulySequenceParams" })
export type CreateHulySequenceParams = Schema.Schema.Type<typeof CreateHulySequenceParamsSchema>

export const UpdateHulyCustomSequenceParamsSchema = Schema.Struct({
  sequence: SequenceIdentifier,
  prefix: HulySequencePrefix,
  confirm: ConfirmSequenceWrite
}).annotate({ title: "UpdateHulyCustomSequenceParams" })
export type UpdateHulyCustomSequenceParams = Schema.Schema.Type<typeof UpdateHulyCustomSequenceParamsSchema>

export const DeleteHulySequenceParamsSchema = Schema.Struct({
  sequence: SequenceIdentifier,
  expectedCurrentValue: Schema.Literal(0).annotate({
    description:
      "Must be 0. Only a never-used sequence can be deleted, and deletion is refused if its counter advanced."
  }),
  confirm: ConfirmSequenceWrite
}).annotate({ title: "DeleteHulySequenceParams" })
export type DeleteHulySequenceParams = Schema.Schema.Type<typeof DeleteHulySequenceParamsSchema>

export const CreateHulySequenceResultSchema = Schema.Struct({
  sequence: HulySequenceSummarySchema,
  created: Schema.Boolean
})
export type CreateHulySequenceResult = Schema.Schema.Type<typeof CreateHulySequenceResultSchema>

export const UpdateHulyCustomSequenceResultSchema = Schema.Struct({
  sequence: HulySequenceSummarySchema,
  updated: Schema.Boolean
})
export type UpdateHulyCustomSequenceResult = Schema.Schema.Type<typeof UpdateHulyCustomSequenceResultSchema>

export const DeleteHulySequenceResultSchema = Schema.Struct({ sequenceId: HulySequenceId, deleted: Schema.Boolean })
export type DeleteHulySequenceResult = Schema.Schema.Type<typeof DeleteHulySequenceResultSchema>

const sequenceWriteConfirmationDescription =
  "Must be true to acknowledge that this operation changes a Huly sequence definition."

export const createHulySequenceParamsJsonSchema = withJsonSchemaUnionPropertyDescriptions(
  toDraft07JsonSchema(CreateHulySequenceParamsSchema),
  {
    class: "Attached class ID, exact class name, or exact class label.",
    kind: "Sequence kind: standard or custom.",
    prefix: "Prefix added to identifiers generated by a custom sequence.",
    confirm: sequenceWriteConfirmationDescription
  }
)
export const updateHulyCustomSequenceParamsJsonSchema = withJsonSchemaPropertyDescriptions(
  toDraft07JsonSchema(UpdateHulyCustomSequenceParamsSchema),
  {
    sequence: "Exact sequence ID or attached class ID or name.",
    prefix: "New prefix added to identifiers generated by the custom sequence.",
    confirm: sequenceWriteConfirmationDescription
  }
)
export const deleteHulySequenceParamsJsonSchema = withJsonSchemaPropertyDescriptions(
  toDraft07JsonSchema(DeleteHulySequenceParamsSchema),
  {
    sequence: "Exact sequence ID or attached class ID or name.",
    expectedCurrentValue: "Must be 0; only a never-used sequence can be deleted.",
    confirm: sequenceWriteConfirmationDescription
  }
)

const strictParseOptions = { onExcessProperty: "error" } as const
export const parseCreateHulySequenceParams = Schema.decodeUnknownEffect(
  CreateHulySequenceParamsSchema,
  strictParseOptions
)
export const parseUpdateHulyCustomSequenceParams = Schema.decodeUnknownEffect(
  UpdateHulyCustomSequenceParamsSchema,
  strictParseOptions
)
export const parseDeleteHulySequenceParams = Schema.decodeUnknownEffect(
  DeleteHulySequenceParamsSchema,
  strictParseOptions
)
